version: '3'
services:
  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    image: strapi:latest
    restart: always
    env_file: .env
    ports:
      - '1337:1337'
